### ISSUE TITLE
CentOS 6.3 -> FATAL: Chef::Exceptions::EnclosingDirectoryDoesNotExist: file[C:/etc/sensu/ssl/cert.pem] (sensu::default line 71)

### ISSUE THREAD

**Issue by uditjh** [sensu/sensu-chef#346] opened 2015-05-19 18:27 UTC
The cookbook doesn't run on CentOS. It fails and for some reason uses the windows attribute.

[2015-05-19T18:08:09+00:00] FATAL: Chef::Exceptions::EnclosingDirectoryDoesNotExist: file[C:/etc/sensu/ssl/cert.pem] (sensu::default line 71) had an error: Chef::Exceptions::EnclosingDirectoryDoesNotExist: Parent directory C:/etc/sensu/ssl does not exist.

Resource Declaration:
---------------------
# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/sensu/recipes/default.rb

 71:   file node.sensu.rabbitmq.ssl.cert_chain_file do
 72:     content ssl["client"]["cert"]
 73:     owner node.sensu.admin_user
 74:     group node.sensu.group
 75:     mode 0640
 76:   end
 77:

Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/sensu/recipes/default.rb:71:in `from_file'

file("C:/etc/sensu/ssl/cert.pem") do
  provider Chef::Provider::File
  action "create"
  retries 0
  retry_delay 2
  path "C:/etc/sensu/ssl/cert.pem"
  backup 5
  cookbook_name :sensu
  recipe_name "default"
  content "-----BEGIN CERTIFICATE-----\nMIIC3TCCA=\n-----END CERTIFICATE-----\n"
  group "sensu"
  mode 416
  owner "Administrator"
end

**Comment by cwjohnston** [comment] 2016-02-03 00:36
Closing as we've been unable to reproduce this issue. If you are still encountering this problem, please open a new issue with more information about how it can be reproduced.

**Closed by cwjohnston** 2016-02-03 00:36 UTC
