### ISSUE TITLE
sensu-client service doesn't seem to be restarting on changes

### ISSUE THREAD

**Issue by dcparker88** [sensu/sensu-chef#381] opened 2015-10-20 15:22 UTC
I have been looking in to this issue for a few days, and can't seem to figure out what's wrong.

When I deploy a new check, or even edit the config.json, chef is not restarting the sensu-client service.

I see the `ruby_block[sensu_service_trigger]` being triggered, which according to [this](https://github.com/sensu/sensu-chef/blob/master/providers/service.rb#L53) I would think would trigger a restart. 

I verified that a manual restart loads the changes checks like expected. 
We are running the latest version (2.10.0)

Please let me know if I am missing something, and I will continue to look in to this.

**Comment by skymob** [comment] 2015-11-02 17:38
I'm seeing the same behavior. I tried running chef-client in debug mode, but it didn't give me much insight into what that ruby_block is evaluating to. 

```
Recipe: sensu::default
  * ruby_block[sensu_service_trigger] action create[2015-11-02T17:32:14+00:00] INFO: Processing ruby_block[sensu_service_trigger] action create (sensu::default line 20)
[2015-11-02T17:32:14+00:00] INFO: ruby_block[sensu_service_trigger] called

    - execute the ruby block sensu_service_trigger
```

We're using chef-client 11.16.4 and the latest sensu-chef cookbook.

**Comment by skymob** [comment] 2015-11-06 22:11
@dcparker88 I resolved this on my end by making sure I was including `sensu::client_service` in my runlist.

**Comment by dcparker88** [comment] 2015-11-07 17:46
thanks for the tip! that doesn't seem to work for me either, but I am trying some other things.

**Comment by scalp42** [comment] 2015-12-17 01:05
Same issue here as well. Investigating.

**Comment by scalp42** [comment] 2015-12-17 01:10
@martinisoft  Can confirm:

```
  * file[/etc/sensu/config.json] action create
    - update content in file /etc/sensu/config.json from d56eb9 to 8b3922
    --- /etc/sensu/config.json	2015-12-17 01:02:42.264748333 +0000
    +++ /etc/sensu/.config.json20151217-19068-126nl1r	2015-12-17 01:04:42.418301783 +0000
    @@ -3,7 +3,7 @@
         "reconnect_on_error": true
       },
       "rabbitmq": {
    -    "host": "redacteeed",
    +    "host": "redacted",
         "port": 5671,
         "vhost": "/sensu",
         "user": "sensu",

Recipe: sensu::client_service
  * sensu_service[sensu-client] action start
```

There's no restart anywhere. I also noticed that if you stop sensu service, the cookbook does not start the service anymore.

**Comment by scalp42** [comment] 2015-12-17 01:13
```
root@consul-i-c7296503 [gz-infra] ~ # service sensu-client status
 * sensu-client is stopped
root@consul-i-c7296503 [gz-infra] ~ # chef-client -o gz-sensu

## REDACTED

Recipe: sensu::client_service
  * sensu_service[sensu-client] action start
```

And you'll see the service not started (can start by hand though):

```
root@consul-i-c7296503 [gz-infra] ~ # service sensu-client status
 * sensu-client is stopped

root@consul-i-c7296503 [gz-infra] ~ # service sensu-client start
 * Starting sensu-client                                                                                                                                                                                                                                                 [ OK ]
root@consul-i-c7296503 [gz-infra] ~ # service sensu-client status
 * sensu-client (pid 26451) is running
```

**Comment by scalp42** [comment] 2015-12-17 01:26
I think the culprit is https://github.com/sensu/sensu-chef/blob/d8c97bf77af82e4e870514d088a85e12261a824f/providers/json_file.rb#L6-L8

returning `false` even when the block exists.

**Comment by icebourg** [comment] 2016-01-08 18:47
Definitely seeing the same issue. No service restarts.

**Comment by cwjohnston** [comment] 2016-02-03 01:03
This sounds like a bug that needs further review.

@scalp42 can you please provide some additional detail around your attempted changes to fix the resource detection block in the `sensu_json_file` provider?

**Comment by cwjohnston** [comment] 2016-03-04 23:06
@scalp42 @icebourg @dcparker88 Is this still an issue for you? I haven't reproduced this in my test environment.

**Comment by icebourg** [comment] 2016-03-04 23:07
Yup, definitely still an issue. We're running 2.11.0 which looks to be the latest version in master.

**Comment by cwjohnston** [comment] 2016-03-04 23:08
@icebourg Chef version?

**Comment by icebourg** [comment] 2016-03-04 23:14
Looks like Chef 12.6.0 works great, but 12.3.0 does not.

**Comment by scalp42** [comment] 2016-03-04 23:17
Not seeing the issue anymore, on Chef `12.7.2` here.

**Comment by cwjohnston** [comment] 2016-03-04 23:18
Thanks folks! Closing.

**Closed by cwjohnston** 2016-03-04 23:18 UTC
Labels: bug, question
