### ISSUE TITLE
gem 'pg' could not be installed

### ISSUE THREAD

**Issue by Entea** [sensu/sensu-chef#270] opened 2014-08-22 08:18 UTC
```
/opt/sensu/embedded/bin/gem install pg -q --no-rdoc --no-ri
Building native extensions.  This could take a while...
ERROR:  Error installing pg:
        ERROR: Failed to build gem native extension.

    /opt/sensu/embedded/bin/ruby extconf.rb
checking for pg_config... yes
Using config values from /usr/bin/pg_config
checking for libpq-fe.h... yes
checking for libpq/libpq-fs.h... yes
checking for pg_config_manual.h... yes
checking for PQconnectdb() in -lpq... no
checking for PQconnectdb() in -llibpq... no
checking for PQconnectdb() in -lms/libpq... no
Can't find the PostgreSQL client library (libpq)
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/sensu/embedded/bin/ruby
        --with-pg
        --without-pg
        --with-pg-config
        --without-pg-config
        --with-pg_config
        --without-pg_config
        --with-pg-dir
        --without-pg-dir
        --with-pg-include
        --without-pg-include=${pg-dir}/include
        --with-pg-lib
        --without-pg-lib=${pg-dir}/
        --with-pqlib
        --without-pqlib
        --with-libpqlib
        --without-libpqlib
        --with-ms/libpqlib
        --without-ms/libpqlib


Gem files will remain installed in /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/pg-0.17.1 for inspection.
Results logged to /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/pg-0.17.1/ext/gem_make.out
```

**Comment by bkett** [comment] 2015-01-27 22:09
This issue is not related to sensu but is caused by 1) the postgres cookbook and 2) because of chef-omnibus. 
There is a pending issue with chef 12.03 (https://github.com/hw-cookbooks/postgresql/issues/212#issuecomment-66508716) and this issue also exists with chef 11.x unless you include build-essential and set it to run at compile time. Also make sure you have the latest version of the postgresql cookbook.

**Comment by mateodelnorte** [comment] 2015-02-18 22:01
I'm doing a `/opt/sensu/embedded/bin/gem install pg` on CentOS 7 using ansible for deployment - no chef. Seeing the same issue. 

Ruby version `ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-linux]`

Should have all the necessary libs `yum`-installed:
```
postgresql.x86_64                       9.2.7-1.el7                    @base
postgresql-devel.x86_64                 9.2.7-1.el7                    @base
postgresql-libs.x86_64                  9.2.7-1.el7                    @base
postgresql-server.x86_64                9.2.7-1.el7                    @base
libpqxx.x86_64                          1:4.0.1-1.el7                  @epel
libpqxx-devel.x86_64                    1:4.0.1-1.el7                  @epel
```

Anyone have ideas for a fix on CentOS 7?

**Comment by bkett** [comment] 2015-02-19 20:20
@mateodelnorte So even though I mentioned Chef specifically, this issue can still rear its head and it's for the same underlying reasons. Namely that you are missing some requisite C/C++ libraries and need to install the CentOS equivalent of build-essential 
```bash
yum groupinstall "Development Tools"
```
I don't know if Ansible playbooks have an option for something to be done at compile-time but if they do then you should consider running this install before installing postgres.

**Comment by bkett** [comment] 2015-02-19 20:26
@mateodelnorte Also this isn't the right place for non-chef related inquiries, you should seek help for this within the ansible community :)

**Comment by mateodelnorte** [comment] 2015-02-19 20:53
Feel free to close. Thanks, all.

**Comment by sulphur** [comment] 2015-06-22 17:31
apparently it might be linked to openssl and the fact that embeded sensu ruby and postgres are not compiled against the same version 

https://groups.google.com/forum/#!topic/ruby-pg/oCo8hDHR16A

**Comment by cwjohnston** [comment] 2016-02-02 23:36
Closing this, as by now this is something of a known issue with Chef and installing the 'pg' gem into any omnibus Ruby environment. 

See https://github.com/hw-cookbooks/postgresql/blob/v4.0.0/recipes/ruby.rb and/or https://gist.github.com/eheydrick/c16f85f7ab8a2a9d3c5d for example implementations of installing this gem into such an environment.

**Closed by cwjohnston** 2016-02-02 23:36 UTC

**Comment by HackToHell** [comment] 2016-02-06 07:34
getting this issue with postgres 9.5 in ubuntu 14.04, without using Chef. Have all the libraries installed.

**Comment by mowings** [comment] 2018-01-04 04:49
This is absolutely not an issue with chef. Same issue with an embedded gem install manually. Ubuntu 16.04
