### ISSUE TITLE
RabbitMQ clustering on client not supported?

### ISSUE THREAD

**Issue by RyanJarv** [sensu/sensu-chef#461] opened 2016-07-04 20:09 UTC
It looks like node['sensu']['rabbitmq'] is always assumed to be a hash which doesn't allow you do create the config with sensu::base_config as described here: https://sensuapp.org/docs/latest/reference/rabbitmq.html#configure-sensu-to-use-the-rabbitmq-cluster

**Comment by RyanJarv** [comment] 2016-07-04 20:26
Ok, quick follow up. I guess just adding the config to the additional attribute of the client resource will work. If this is the right way to do it maybe worth adding something to the README about this?

**Comment by cwjohnston** [comment] 2016-08-01 20:18
Hi @RyanJarv, thanks for reporting this issue. I'm glad you were able to determine a workaround with `sensu_snippet`. We are planning to improve on the situation you've described, but I'm going to close this issue as a duplicate of #363.

**Closed by cwjohnston** 2016-08-01 20:18 UTC
