### ISSUE TITLE
Missing Databag issue with Chef 12.7.2

### ISSUE THREAD

**Issue by aaronblythe** [sensu/sensu-chef#406] opened 2016-02-16 21:37 UTC
When running a 'kitchen converge' on chef 12.7.2 of a slightly modified https://github.com/portertech/chef-monitor that converges on chef 12.6.0 I get:

    ================================================================================
       Recipe Compile Error in /tmp/kitchen/cookbooks/monitor/recipes/master.rb
       ================================================================================
       
       NoMethodError
       -------------
       undefined method `delete' for nil:NilClass
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cookbooks/sensu/libraries/sensu_helpers.rb:40:in `data_bag_item'
         /tmp/kitchen/cookbooks/sensu/recipes/rabbitmq.rb:88:in `from_file'
         /tmp/kitchen/cookbooks/monitor/recipes/master.rb:20:in `from_file'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cookbooks/sensu/libraries/sensu_helpers.rb:
       
        33:            "/opt/sensu/embedded/bin/gem"
        34:          else
        35:            "gem"
        36:          end
        37:        end
        38:  
        39:        def data_bag_item(item, missing_ok=false, data_bag_name="sensu")
        40>>         raw_hash = Chef::DataBagItem.load(data_bag_name, item)
        41:          encrypted = raw_hash.detect do |key, value|
        42:            if value.is_a?(Hash)
        43:              value.has_key?("encrypted_data")
        44:            end
        45:          end
        46:          if encrypted
        47:            if Chef::DataBag.load(data_bag_name).key? "#{item}_keys"
        48:              chef_vault_item(data_bag_name, item)
        49:            else

It seems the recent change of the way that data bags are loaded:
* https://github.com/chef/chef/commit/d99e306a41b1402209d320cb7119b12a3bbb962f#diff-143e680ed6057de0f7066c7b539a7d28R131

Causes an issue when loading the "config_item" data bag item if it is not defined

* https://github.com/sensu/sensu-chef/blob/master/recipes/rabbitmq.rb#L88

I don't see where this is documented as to what to populate this data bag with either in this project's README or https://github.com/jjasghar/rabbitmq

either one of these solutions get me back in business for the short term:

1) updating the .kitchen.yml in chef-monitor to:

    driver_config:
      require_chef_omnibus: 12.6.0

2) updating the chef-monitor project to have a test/integration/data_bags/sensu/config.json with:

    {
      "id": "config"
    }

Further a server.json, api.json, and client.json are also needed to fully converge.

Curious what the format of these data bags should actually be or if they are needed at all.

**Comment by jeremysmitherman** [comment] 2016-02-16 22:16
Yeah the whole idea of having the keys inline is a terrible pattern.  Would be better if we could just point them to a file.

**Comment by mool** [comment] 2016-02-22 14:23
I'm having the same problem. Using chef 12.6.0 works fine.

**Comment by luckymike** [comment] 2016-03-02 23:47
@aaronblythe Have you opened an issue with Chef for this apparent regression? It would be good to confirm if this is a bug or an intended loss of functionality before we attempt to implement a solution.

Also, the recipe you've referenced is not part of this cookbook, it is the monitor cookbook: https://github.com/portertech/chef-monitor (last updated 2013), so the code in question may no longer be relevant or maintained.

**Comment by aaronblythe** [comment] 2016-03-03 04:23
@luckymike thank you for the follow up and I agree.

As far as the potential Chef regression, I believe it has been logged as this issue: https://github.com/chef/chef/issues/4602 and is likely from this merge: https://github.com/chef/chef/commit/a028bda72981a9b58427054d51d69a58b45badc2 .  Maybe this is chef-solo only issue?

I mentioned the chef-monitor cookbook since I am using a fork of it and it is a popular starting point for others. It exercises the issue logged with only a couple modifications to get it back to working.

So now to the sensu cookbook, the part I am trying to understand better is that:
https://github.com/sensu/sensu-chef/blob/master/recipes/rabbitmq.rb#L88 sends off to a helper method https://github.com/sensu/sensu-chef/blob/master/libraries/sensu_helpers.rb#L39 setting missing_ok=true.  Since Chef has changed it is no longer ok that the data bag is missing :) Hopefully the potential regression is patched.  If not then a data bag is needed even if it is empty.  Not a huge blocker since it is fairly simple to work around, however worth discussion and possibly an update to the helper method to match the parameter semantics if the Chef change was intentional. 

It would still help to have better documentation on what to put in those data bags either way. ;)

**Comment by luckymike** [comment] 2016-03-03 16:38
Thanks for the additional detail. I think the best solution we can provide is means to skip the data bag item for rabbitmq entirely in your wrapper. We've just merged support to do that to develop:

https://github.com/sensu/sensu-chef/pull/410/files

Does that provide the facility you need to route around this bug? If so, you should be able to look forward to a release very soon. :)

**Comment by cwjohnston** [comment] 2016-08-01 17:52
Closing this due to inactivity, please open a new issue if the changes in #410 are insufficient.

**Closed by cwjohnston** 2016-08-01 17:52 UTC
Labels: enhancement
